import { QUESTIONNAIRES } from './questionnaires';

export const INTEGRATION_DOMAINS = [
  'Atencao',
  'Hiperatividade e impulsividade',
  'Funcoes executivas',
  'Leitura e escrita',
  'Aspectos emocionais',
  'Relacionamento social',
  'Comunicacao social',
  'Sensorialidade',
  'Autonomia',
];

export const INVESTIGATIVE_HYPOTHESES = [
  'TDAH',
  'TEA',
  'Ansiedade social',
  'Sintomas emocionais internalizantes',
  'Sintomas depressivos',
  'Dificuldade de atencao sustentada',
  'Dificuldade de controle inibitorio',
  'Dificuldade de organizacao',
  'Alteracoes de funcoes executivas',
  'Dificuldades de relacionamento',
  'Repercussoes do bullying',
  'Dificuldades ortograficas',
  'Dificuldade de acesso lexical',
  'Alteracoes de memoria de trabalho',
  'Transtorno especifico da aprendizagem',
];

const adolescentInstrument = {
  ageRange: 'Adolescentes; confirmar no manual',
  agePolicy: 'manual-confirmation',
  contentStatus: 'metadata-only',
  normativeStatus: 'descriptive-unless-manual',
  limitation: 'O resultado nao confirma diagnostico isoladamente.',
};

const instrumentCatalog = [
  {
    ...adolescentInstrument,
    id: 'conners-pais-42',
    name: 'Escala Conners - Pais, 42 itens',
    shortName: 'Conners Pais',
    description: 'Rastreio de indicadores comportamentais e atencionais por relato dos responsaveis.',
    informants: ['Responsavel'],
    application: 'Individual, entrevista ou formulario autorizado.',
    duration: '15 a 25 min',
    domains: ['Atencao', 'Hiperatividade e impulsividade', 'Aspectos emocionais', 'Relacionamento social'],
    scoring: 'Registrar escores por area conforme a versao utilizada.',
  },
  {
    ...adolescentInstrument,
    id: 'ele',
    name: 'Escala de Leitura e Escrita - ELE',
    shortName: 'ELE',
    description: 'Registro de desempenho academico em leitura, escrita e habilidades relacionadas.',
    informants: ['Professor', 'Profissional'],
    application: 'Aplicacao individual com protocolo autorizado.',
    duration: '25 a 40 min',
    domains: ['Leitura e escrita', 'Funcoes executivas'],
    scoring: 'Registrar acertos, erros, omissoes e porcentagens conforme o protocolo.',
  },
  {
    ...adolescentInstrument,
    id: 'mchat-rf',
    name: 'M-CHAT-R/F',
    shortName: 'M-CHAT-R/F',
    description: 'Modulo infantil separado. Nao e destinado a adolescentes.',
    informants: ['Responsavel', 'Profissional'],
    application: 'Aplicacao infantil conforme manual oficial.',
    duration: 'Conforme manual',
    ageRange: 'Modulo infantil; bloqueado para adolescentes',
    agePolicy: 'blocked-for-adolescents',
    domains: ['Comunicacao social', 'Relacionamento social'],
    scoring: 'Nao disponibilizar para este aplicativo de adolescentes.',
    limitation: 'Aplicacao bloqueada para adolescentes. Usar somente em contexto infantil autorizado.',
  },
  {
    ...adolescentInstrument,
    id: 'sdq',
    name: 'SDQ - Capacidades e Dificuldades',
    shortName: 'SDQ',
    description: 'Questionario de dificuldades, capacidades e impacto com multiplos informantes.',
    informants: ['Professor', 'Responsavel', 'Adolescente'],
    application: 'Formulario por informante, conforme a versao utilizada.',
    duration: '10 a 15 min',
    domains: ['Aspectos emocionais', 'Atencao', 'Relacionamento social', 'Hiperatividade e impulsividade'],
    scoring: 'Registrar subescalas, total e impacto separadamente.',
  },
  {
    ...adolescentInstrument,
    id: 'snap-iv-escola',
    name: 'SNAP-IV - Escola',
    shortName: 'SNAP-IV Escola',
    description: 'Registro escolar de indicadores de desatencao e hiperatividade/impulsividade.',
    informants: ['Professor'],
    application: 'Formulario respondido pelo professor ou profissional autorizado.',
    duration: '10 a 15 min',
    domains: ['Atencao', 'Hiperatividade e impulsividade'],
    scoring: 'Registrar resultados por subescala sem inferir diagnostico.',
  },
  {
    ...adolescentInstrument,
    id: 'rastreio-tdah-adolescente',
    name: 'Rastreio de TDAH para adolescente',
    shortName: 'Rastreio TDAH',
    description: 'Rastreio descritivo para organizar indicadores que precisam de investigacao.',
    informants: ['Adolescente', 'Profissional'],
    application: 'Entrevista ou protocolo autorizado.',
    duration: '15 a 25 min',
    domains: ['Atencao', 'Hiperatividade e impulsividade', 'Funcoes executivas'],
    scoring: 'Resultado descritivo; nao usar classificacao normativa sem manual.',
  },
  {
    ...adolescentInstrument,
    id: 'tda-hiperatividade',
    name: 'TDA - Hiperatividade fisica e mental',
    shortName: 'TDA Hiperatividade',
    description: 'Organiza indicadores de hiperatividade fisica e mental relatados pelo adolescente.',
    informants: ['Adolescente'],
    application: 'Entrevista ou protocolo autorizado.',
    duration: '15 a 20 min',
    domains: ['Hiperatividade e impulsividade', 'Atencao', 'Funcoes executivas'],
    scoring: 'Resultado descritivo por area.',
  },
  {
    ...adolescentInstrument,
    id: 'prova-atencao-concentracao',
    name: 'Prova de atencao e concentracao',
    shortName: 'Atencao e concentracao',
    description: 'Registro de acertos, erros e omissoes em tarefa de atencao.',
    informants: ['Adolescente'],
    application: 'Aplicacao individual em condicoes registradas pela profissional.',
    duration: '15 a 30 min',
    domains: ['Atencao', 'Funcoes executivas'],
    scoring: 'Registrar acertos, erros, omissoes e observacoes qualitativas.',
  },
  {
    ...adolescentInstrument,
    id: 'questionario-funcoes-executivas',
    name: 'Questionario de atencao e funcoes executivas',
    shortName: 'Funcoes executivas',
    description: 'Questionario para registrar frequencia de indicadores executivos e atencionais.',
    informants: ['Adolescente', 'Responsavel', 'Professor'],
    application: 'Formulario por informante conforme protocolo autorizado.',
    duration: '15 a 25 min',
    domains: ['Atencao', 'Funcoes executivas', 'Autonomia'],
    scoring: 'Registrar frequencias por area e informante.',
  },
  {
    ...adolescentInstrument,
    id: 'rastreio-tea-10',
    name: 'Rastreio TEA-10 para adolescentes',
    shortName: 'Rastreio TEA-10',
    description: 'Modelo adaptado de rastreio investigativo de comunicacao social e relacionamento.',
    informants: ['Adolescente', 'Responsavel'],
    application: 'Entrevista ou formulario autorizado.',
    duration: '15 a 25 min',
    domains: ['Comunicacao social', 'Relacionamento social', 'Sensorialidade', 'Autonomia'],
    scoring: 'DT e DP = 0; CP e CT = 1. Faixas descritivas do modelo, sem diagnostico automatico.',
    questionnaire: {
      title: 'AQ-10 - Questionario de rastreio para adolescentes',
      note: 'Este modelo organiza dominios investigados em triagens de TEA. Nao corresponde a reproducao literal de instrumento oficial protegido.',
      scoringMode: 'raw',
      maximum: 10,
      options: [
        { id: 'CT', label: 'Concordo totalmente', score: 1 },
        { id: 'CP', label: 'Concordo parcialmente', score: 1 },
        { id: 'DP', label: 'Discordo parcialmente', score: 0 },
        { id: 'DT', label: 'Discordo totalmente', score: 0 },
      ],
      items: [
        'Dificuldade para perceber pistas sociais sutis, como expressoes faciais, tom de voz ou mudancas no comportamento das pessoas.',
        'Costuma interpretar falas, brincadeiras, ironias ou indiretas de maneira muito literal.',
        'Demonstra desconforto para iniciar, manter ou finalizar conversas com colegas ou pessoas pouco conhecidas.',
        'Prefere rotinas previsiveis e pode se incomodar quando ocorrem mudancas inesperadas.',
        'Demonstra resistencia, irritacao, ansiedade ou sofrimento diante de mudancas de planos, ambientes ou combinados.',
        'Apresenta interesses muito intensos, especificos ou restritos, falando ou pensando repetidamente sobre determinados temas.',
        'Mostra sensibilidade aumentada a sons, luzes, cheiros, texturas, toque, etiquetas de roupas ou ambientes muito movimentados.',
        'Tem dificuldade para compreender regras sociais implicitas, como saber o momento adequado de falar, parar, brincar ou mudar de assunto.',
        'Relata ou demonstra sensacao de nao pertencimento, deslocamento social ou dificuldade para se sentir conectado aos grupos.',
        'Prefere atividades solitarias ou interacoes mais previsiveis, evitando situacoes sociais muito abertas ou imprevisiveis.',
      ],
      ranges: [
        { range: '0 a 2', percentage: '0% a 20%', label: 'Poucos indicadores no rastreio' },
        { range: '3 a 5', percentage: '30% a 50%', label: 'Indicadores leves a moderados' },
        { range: '6 a 10', percentage: '60% a 100%', label: 'Indicadores relevantes para investigacao' },
      ],
    },
  },
];

export const INSTRUMENTS = instrumentCatalog.map((instrument) => ({
  ...instrument,
  questionnaire: QUESTIONNAIRES[instrument.id] || instrument.questionnaire,
  contentStatus: QUESTIONNAIRES[instrument.id] ? 'source-imported' : instrument.contentStatus,
}));
